CONFIG_VARS += RF24_MINIMAL
RF24_MINIMAL ?= 0
ifeq (RF24_MINIMAL,1)
COMPONENT_CPPFLAGS += -DRF24_MINIMAL=1
endif

CONFIG_VARS += RF24_FAILURE_HANDLING
RF24_FAILURE_HANDLING ?= 0
ifeq (RF24_FAILURE_HANDLING,1)
COMPONENT_CPPFLAGS += -DRF24_FAILURE_HANDLING=1
endif
